/**
 * News post data model.
 * 
 * Represents a news article in the Firestore news collection.
 */

export interface NewsPostDoc {
    /** Unique document ID (auto-generated by Firestore) */
    id?: string;
    
    /** News article title */
    title: string;
    
    /** URL-friendly slug for the article */
    slug: string;
    
    /** News category */
    category: 'general' | 'update' | 'event' | 'maintenance';
    
    /** URL to the featured image */
    imageUrl: string;
    
    /** Short excerpt/description */
    excerpt: string;
    
    /** Full article content (HTML or markdown) */
    content: string;
    
    /** Author's user ID */
    authorId: string;
    
    /** Author's display name */
    authorName: string;
    
    /** Publication timestamp */
    publishedAt: any; // Firestore Timestamp
    
    /** Whether this is a featured/important news item */
    featured: boolean;
    
    /** Array of tags for categorization */
    tags: string[];
    
    /** Language code (2-letter ISO) */
    lang: string;
}
